"""add_tags_table

Revision ID: d046a94c9f79
Revises: 6c7537a6004a
Create Date: 2018-12-14 16:42:54.400136

"""

# revision identifiers, used by Alembic.
revision = 'd046a94c9f79'
down_revision = '6c7537a6004a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tag_name', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tag_name'),
    )
    op.create_table('dashboard_tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=True),
        sa.Column('dashboard_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
